version: '3.8'

services:
   mongo:
    build: ./mongodb
    restart: always
    ports: 
     - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    volumes:
     - ./db/:/data/db
     - ./mongodb/:/etc/mongo